### ISSUE TITLE
Server crashing on startup 1.20.4

### ISSUE THREAD

**Issue by NoHating3990** [Patbox/Image2Map#45]
Idk if has been said but once I installed the mod into the server it did not work and crashed the server right on start up

Image2Map Version: 0.6.0 - 1.20.6
Server Version: 1.20.4
Fabric Loader: 0.15.11

Other mods: Fabric API 0.97.0

Fabric Server Loader log

```java
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.server.Main.main(Main.java:106)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5537 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_6089.method_9530(class_6089.java:65)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114)
	at net.minecraft.class_4970.method_9549(class_4970.java:405)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1253)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for image2map.mixins.json:BundleItemMixin from mod image2map during activity: [Transform -> Method image2map$useBundle(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> GETSTATIC -> net/minecraft/class_9334::field_49628:Lnet/minecraft/class_9331;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.class_9334
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 28 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_9334
	... 32 more

``` 

CMD Log:

```java

D:\MC server>java -Xmx4G -jar fabric-server-mc.1.20.4-loader.0.15.11-launcher.1.0.1.jar
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[08:16:57] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[08:16:57] [main/INFO]: Loading 46 mods:
        - fabric-api 0.97.0+1.20.4
           |-- fabric-api-base 0.4.37+78d798af4f
           |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
           |-- fabric-biome-api-v1 13.0.17+78d798af4f
           |-- fabric-block-api-v1 1.0.17+3e2216cb4f
           |-- fabric-block-view-api-v2 1.0.5+78d798af4f
           |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
           |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
           |-- fabric-command-api-v1 1.2.42+f71b366f4f
           |-- fabric-command-api-v2 2.2.21+78d798af4f
           |-- fabric-commands-v0 0.2.59+df3654b34f
           |-- fabric-containers-v0 0.1.87+df3654b34f
           |-- fabric-content-registries-v0 5.0.16+78d798af4f
           |-- fabric-convention-tags-v1 1.5.11+78d798af4f
           |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
           |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
           |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
           |-- fabric-dimensions-v1 2.1.62+78d798af4f
           |-- fabric-entity-events-v1 1.6.2+09fc25014f
           |-- fabric-events-interaction-v0 0.7.2+389931eb4f
           |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
           |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
           |-- fabric-item-api-v1 2.3.0+bcdd12964f
           |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
           |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
           |-- fabric-keybindings-v0 0.2.40+df3654b34f
           |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
           |-- fabric-loot-api-v2 2.1.10+78d798af4f
           |-- fabric-message-api-v1 6.0.6+78d798af4f
           |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
           |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
           |-- fabric-models-v0 0.4.8+9386d8a74f
           |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
           |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
           |-- fabric-particles-v1 1.1.8+78d798af4f
           |-- fabric-recipe-api-v1 2.0.21+78d798af4f
           |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
           |-- fabric-renderer-api-v1 3.2.5+78d798af4f
           |-- fabric-renderer-indigo 1.5.5+78d798af4f
           |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
           |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
           |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
           |-- fabric-rendering-v0 1.1.57+df3654b34f
           |-- fabric-rendering-v1 3.2.1+6fd945a04f
           |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
           |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
           |-- fabric-screen-api-v1 2.0.18+78d798af4f
           |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
           |-- fabric-sound-api-v1 1.0.18+78d798af4f
           |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
           \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
        - fabricloader 0.15.11
           \-- mixinextras 0.3.5
        - image2map 0.6.0+1.20.6
           |-- map-canvas-api 0.3.0+1.20.6
           \-- sgui 1.5.1+1.20.5
        - java 21
        - lithium 0.12.1
        - minecraft 1.20.4
[08:16:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/MC%20server/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[08:16:58] [main/INFO]: Compatibility level set to JAVA_17
[08:16:58] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 0 override(s) found
[08:16:58] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[08:17:02] [main/WARN]: Error loading class: net/minecraft/class_9334 (java.lang.ClassNotFoundException: net/minecraft/class_9334)
[08:17:02] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5537 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for image2map.mixins.json:BundleItemMixin from mod image2map during activity: [Transform -> Method image2map$useBundle(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> GETSTATIC -> net/minecraft/class_9334::field_49628:Lnet/minecraft/class_9331;]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.class_9334
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_9334
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.minecraft.class_6089.method_9530(class_6089.java:65) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1118) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1114) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970.method_9549(class_4970.java:405) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1391) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:929) ~[server-intermediary.jar:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:1253) ~[server-intermediary.jar:?]
        at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more

```

**Comment by Patbox** [comment]
You are using 1.20.6 version on 1.20.4, use older one
